### ISSUE TITLE
Emails ne s'envoient pas

### ISSUE THREAD

**Issue by ghost** [LaurentP/contact-form#1]
Les emails ne s'envoient pas.

**Comment by LaurentP** [comment]
Bonjour,

Je n'ai pas compris exactement pourquoi les e-mails ne s'envoyaient pas lorsque vous avez essayé ce formulaire, si vous pouvez me donner plus d'informations.

Il faut vérifier que la fonction mail() de PHP soit bien activée.

J'avais aussi configuré XAMPP pour que les e-mails puissent s'envoyer en utilisant Papercut comme logiciel supplémentaire pour ma part.

Je peux vous assurer que dans ces conditions, il fonctionne parfaitement.

Cordialement.

**Comment by ro4n** [comment]
Bonjour,

Après vérification, la fonction mail() est bien activée sur mon site web.

Avez-vous une adresse mail ou un canal sur lequel nous pouvons échanger à ce sujet ?

Bien cordialement,
Romain

**Comment by LaurentP** [comment]
Bonjour,

Nous pouvons échanger ici à ce propos.

Avez-vous des erreurs de PHP qui s'affichent, ou est-ce que le formulaire fonctionne comme il devrait sans que vous voyez les emails dans votre boîte aux lettres ?

Avez-vous aussi regardé dans vos spams ?

Cordialement.

**Comment by ro4n** [comment]
Bonjour,

Il n'y a pas d'erreurs de PHP qui s'affichent, en l'occurrence le formulaire bloque avec le message "Votre message n'a pu être envoyé" lors de la tentative d'envoi.

Bien cordialement,
Romain

**Comment by ro4n** [comment]
Si cela peut vous aider, j'utilise la version 7.0 sous nginx.

**Comment by LaurentP** [comment]
Bonjour,

Ce message d'erreur apparaît car la fonction mail() de PHP n'a pas pu être exécutée. Cela est du à la configuration du serveur.

Avez-vous un serveur SMTP sur la machine qui héberge votre site, et PHP est-il configuré pour fonctionner avec ?
